# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='lemma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='words', to='quran.Lemma'),
        ),
    ]
