# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 05:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0002_word_lemma'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordMeaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttext', models.TextField()),
                ('utext', models.TextField()),
                ('aya_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_meanings', to='quran.Aya')),
                ('sura_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_meanings', to='quran.Sura')),
                ('word_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meaning', to='quran.Aya')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='word',
            name='meaning',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='quran.WordMeaning'),
        ),
    ]
