# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0003_auto_20160526_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordmeaning',
            name='aya_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wordmeaning',
            name='sura_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wordmeaning',
            name='word_number',
            field=models.IntegerField(),
        ),
    ]
