# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 00:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0005_auto_20160526_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordmeaning',
            name='utext',
        ),
    ]
