# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0006_remove_wordmeaning_utext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('aya_begin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quran.Aya')),
                ('aya_end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quran.Aya')),
            ],
        ),
    ]
