# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-02 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0007_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistinctWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttext', models.TextField(blank=True, db_index=True, null=True)),
                ('utext', models.TextField(blank=True, db_index=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('lemma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distinct_words', to='quran.Lemma')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='word',
            name='distinct_word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='words', to='quran.DistinctWord'),
        ),
    ]
