# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-02 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0008_auto_20160602_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='utextmin',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
